### ISSUE TITLE
Is version V3.0.0 out?

### ISSUE THREAD

**Issue by bigardone** [phollyer/elm-phoenix-websocket#1]
Hi! First of all, thanks for such a great package and example. I've been looking for something similar for quite a time.

I want to use it in a project that I'm working on; however, the docs in master refer to a v3.0.0, https://github.com/phollyer/elm-phoenix-websocket/tree/master/js#an-elm-spa, which seems to have not been published yet. Moreover, all the links in the example point to an unexisting `Phoenix` module in the Elm docs, like https://package.elm-lang.org/packages/phollyer/elm-phoenix-websocket/latest/Phoenix#socketState. Is this right, or am I missing anything?

**Comment by phollyer** [comment]
Hi,

You're not missing anything, the problems you mentioned are because V3.0.0 is not yet published. I just have some minor tweaks to the API to do, and want to finish off the examples, then I'll publish V3.0.0 - I'm aiming for the end of the week if not before, and will update here when I have.

Glad you like the package, let me know if you have any other issues :)

**Comment by bigardone** [comment]
Awesome! I'll keep an eye for the new version and let you know if I have any issues 👏

**Comment by phollyer** [comment]
Version 3.0.0 is now published.

Suggestions/feedback are always welcome.

**Comment by bigardone** [comment]
Awesome. I'll start using it this week and let you know about anything!
Cheers!
